@startuml
'https://plantuml.com/activity-diagram-beta

start
:运单中心定时调度;
:查询待分派作业单
和已分派骑手的作业单
（包含运单);
if()then(有)
    :查询运力中心骑手运力;
    :请求调度中心，调度作业单;
    :更新作业单和运单分派结果;
    :更新运单状态，记录状态变更日志;
    :发送获取隐私号消息;
    :通知运力中心，骑手状态;
    :通知履约中心，履行单和作业单状态;
else(无)
stop
endif
stop

@enduml
