@startuml

frame "运单域" {
    object "运单" as D
    object "配送批次单" as P
}

object D {
- 运单号
- 履行单号
- 状态
- 履约单号
'- 订单号
- 用户信息
- 履约时间
- 货品列表
- 货品重量
- 交接箱号List
- 配送服务信息
- 是否第三方配送
- 第三方配送信息
- 配送人信息
- 是否超时
- 是否超区
- SLA
}


object P {
- 批次编号
- 运单号列表
- 配送人信息
- 分派时间
- 揽收时间
- 出发时间
- 签收时间
- 状态
}


@enduml